// <auto-generated />
using System;
using ApiEnvioMasivo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiEnvioMasivo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250601041120_AgregarTrackingCampos")]
    partial class AgregarTrackingCampos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiEnvioMasivo.Models.CorreoEnviado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Abierto")
                        .HasColumnType("bit");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlujoPasoId")
                        .HasColumnType("int");

                    b.Property<int?>("PasoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("FlujoPasoId");

                    b.HasIndex("PasoId");

                    b.ToTable("CorreosEnviados");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.Destinatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicioFlujo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlujoId")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlujoId");

                    b.ToTable("Destinatarios");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.Flujo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flujos");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.FlujoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Abierto")
                        .HasColumnType("bit");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlujoId")
                        .HasColumnType("int");

                    b.Property<bool>("HizoClic")
                        .HasColumnType("bit");

                    b.Property<int>("PasoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.ToTable("FlujoHistoriales");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.FlujoPaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Asunto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionValor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiasDespuesDelInicio")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Espera")
                        .HasColumnType("time");

                    b.Property<int>("FlujoId")
                        .HasColumnType("int");

                    b.Property<string>("HtmlContenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlujoId");

                    b.ToTable("FlujoPasos");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.SuscripcionRequest", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SuscripcionRequest");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.CorreoEnviado", b =>
                {
                    b.HasOne("ApiEnvioMasivo.Models.Destinatario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEnvioMasivo.Models.FlujoPaso", "FlujoPaso")
                        .WithMany()
                        .HasForeignKey("FlujoPasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEnvioMasivo.Models.FlujoPaso", "Paso")
                        .WithMany()
                        .HasForeignKey("PasoId");

                    b.Navigation("Destinatario");

                    b.Navigation("FlujoPaso");

                    b.Navigation("Paso");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.Destinatario", b =>
                {
                    b.HasOne("ApiEnvioMasivo.Models.Flujo", "Flujo")
                        .WithMany()
                        .HasForeignKey("FlujoId");

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.FlujoHistorial", b =>
                {
                    b.HasOne("ApiEnvioMasivo.Models.Destinatario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.FlujoPaso", b =>
                {
                    b.HasOne("ApiEnvioMasivo.Models.Flujo", "Flujo")
                        .WithMany("Pasos")
                        .HasForeignKey("FlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flujo");
                });

            modelBuilder.Entity("ApiEnvioMasivo.Models.Flujo", b =>
                {
                    b.Navigation("Pasos");
                });
#pragma warning restore 612, 618
        }
    }
}
